### ISSUE TITLE
Running_BOOT_BIN_on_Hardware

### ISSUE THREAD

**Issue by saraproctor** [Xilinx/Vitis_Model_Composer#15]
When you click on the link for How to Install Hardware Server on step 7 in [this guide](https://github.com/Xilinx/Vitis_Model_Composer/blob/main/QuickGuides/Running_BOOT_BIN_on_Hardware/README.md#How-to-Install-Hardware-Server),

it takes you to the same location. Please change the link for How to Install Hardware Server on step 7 to https://github.com/Xilinx/Vitis_Model_Composer/blob/main/QuickGuides/Running_BOOT_BIN_on_Hardware/README.md#how-to-install-hardware-server

**Comment by abehbood** [comment]
Hello @saraproctor,

This link is corrected in the new location of this page, 

https://github.com/Xilinx/Vitis_Model_Composer/blob/2022.2/QuickGuides/Running_on_Hardware/baremetal/README.md

Thank you for reporting this issue.

**Comment by abehbood** [comment]
Hello @saraproctor,

This link is corrected in the new location of this page,

https://github.com/Xilinx/Vitis_Model_Composer/blob/2022.2/QuickGuides/Running_on_Hardware/baremetal/README.md

Thank you for reporting this issue.
