### ISSUE TITLE
Is SysGen now VitisModelComposer

### ISSUE THREAD

**Issue by Beauxrel** [Xilinx/Vitis_Model_Composer#16]
I have questions about Vitis Model Composer.

- Is Sysgen rebranded to Vitis Model Composer, or are they 2 different products?
- Will HDL-Coder work with Vitis Model Composer / is it necessary?
- I would like to interface with FMCOMMS3 with my generated design, will this be possible?

Thank you!

**Comment by Beauxrel** [comment]
I ask because a lot of the tutorials mention the zynq processor, but we don't have that in our FPGA.

**Comment by mohammadsdtmnd** [comment]
I think these IP are capable of importing to all amd FPGA block of AMD/Xilinx products. But you can install Vitis to check that in the program by yourself. You can check that. Only generating IP requires lie sense.

**Comment by Beauxrel** [comment]
@mohammadsdtmnd you are correct, however I chose to use HDL Coder instead. Thank you for your reply
