### ISSUE TITLE
lab6_1.h is missing

### ISSUE THREAD

**Issue by RaulAguilarOH** [Xilinx/Vitis_Model_Composer#19]
I am trying to use your lab6 example to do some co-simulation using the kv260 starter kit, but I noticed lab6_1.h file is missing.

**Comment by robgraessle** [comment]
Thanks for pointing this out. The include statement should refer to "hdl_dut.h", which is generated in the IPI Project. References to variables named "lab6_1" also need to be changed to "hdl_dut". We will fix hello_world_final.c. This flow will be changing entirely in 2023.2.
