### ISSUE TITLE
Sine wave HDL bug: output data can't be spectrum analyzed

### ISSUE THREAD

**Issue by mohammadsdtmnd** [Xilinx/Vitis_Model_Composer#37]
By having this: Sinewave -> output gateway -> spectrum analyzer
Hub setting: zynq7000-7020-400-2, FPGA period:1e9/125e6 Simulink period: 1/125e6
Output is visible in scope but not in spectrum analyzer. DSP spectrum analyzer shows nothing, but by checking the propagate data type to output we can see that also in spectrum analyzer, why?

**Comment by cholmber** [comment]
[AMD Official Use Only - General]

Also open a case at support.xilinx.com if your problem persists.

From: Holmberg, Craig
Sent: Friday, March 22, 2024 8:43 AM
To: Xilinx/Vitis_Model_Composer ***@***.***>; Xilinx/Vitis_Model_Composer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: RE: [Xilinx/Vitis_Model_Composer] Sine wave bug: output data can't be spectrum analyzed (Issue #37)

Make sure you run the simulation long enough to collect enough samples for the spectrum analyzer.  Unlike the scope (which can begin displaying in the time domain as you run it) the spectrum analyzer needs sufficient samples to perform the calculations and will not display results until that happens.

Also check the sample times in your entire signal path.  Sounds like you’ve set the signal source time domain but there may be other blocks in the path that reinterpret it.  For instance the ‘Gateway In’ sets sample time annotations.

To get feedback on how the tool is interpreting your sample times I suggest turning on Simulink’s sample time annotations.


From: Seyeed Mohammad Saadatamand ***@***.******@***.***>>
Sent: Friday, March 22, 2024 7:33 AM
To: Xilinx/Vitis_Model_Composer ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: [Xilinx/Vitis_Model_Composer] Sine wave bug: output data can't be spectrum analyzed (Issue #37)

Caution: This message originated from an External Source. Use proper caution when opening attachments, clicking links, or responding.


By having this: Sinewave -> output gateway -> spectrum analyzer
Hub setting: zynq7000-7020-400-2, FPGA period:1e9/125e6 Simulink period: 1/125e6
Output is visible in scope but not in spectrum analyzer. DSP spectrum analyzer shows nothing, but by checking the propagate data type to output we can see that also in spectrum analyzer, why?

**Comment by mohammadsdtmnd** [comment]
> [AMD Official Use Only - General] Make sure you run the simulation long enough to collect enough samples for the spectrum analyzer. Unlike the scope (which can begin displaying in the time domain as you run it) the spectrum analyzer needs sufficient samples to perform the calculations and will not display results until that happens. Also check the sample times in your entire signal path. Sounds lik... are subscribed to this thread.Message ID: ***@***.******@***.***>>


Sorrily, not collecting more sample nor using convert AMD block does not cured the bug.
[test_file.zip](https://github.com/Xilinx/Vitis_Model_Composer/files/14723433/test.zip)
The file uploaded, though this has been run on latest versions, but I have also check that on 2022.2vivado 2021bMatlab.
The only cure is to check propagate data type to output in output gateway.
![image](https://github.com/Xilinx/Vitis_Model_Composer/assets/43541304/528b1dc1-fc63-4fa5-b64c-ac894ff35537)

**Comment by abehbood** [comment]
Hello @mohammadsdtmnd ,

Thank you for sharing your design. Looking at it more carefully, I noticed that the output of the subsystem has two NaN elements in it. Apparently, Simulink spectrum analyzer does not behave correctly when there is NaN in the signal, yet, it does not complain about it either. So, I added a simple MATLAB function block to remove any NaN from the signal and the Spectrum Analyzer started working. 

![image](https://github.com/Xilinx/Vitis_Model_Composer/assets/72752619/a5ec7fbf-9f36-47e9-bd8c-c862f0b7ffee)

Here is the code in the MATLAB function block:

```
function y = fcn(u)

if isnan(u)
    y = 0;
else 
    y = u;
end
```

Hope this answered your question. 

Thanks

**Comment by mohammadsdtmnd** [comment]
Dear @abehbood 
Absolute answer, THX so much. This means output of sinewave block does contain bug that produces NaN in its output. Also have you noticed that the output frequency is double the frequency you have assigned to this block?
This is bug and I can't understand why it is present in 2022.2 and 2023.2 both. Also no documentation about theory of operation of this block?!
